backend:
  name: git-gateway
  branch: main

media_folder: "."
public_folder: "/"
site_url: https://cozy-twilight-20476f.netlify.app

collections:
  - name: pages
    label: Pages
    folder: ""
    create: false
    files:
      - name: index
        label: Home
        file: index.html
        fields:
          - { name: title, label: Page Title, widget: string }
      - name: about
        label: About
        file: about.html
        fields:
          - { name: title, label: Page Title, widget: string }
