backend:
  name: github
  repo: turguthamid/turguthamid-site
  branch: main
  base_url: https://cozy-twilight-20476f.netlify.app
  auth_endpoint: api/auth

media_folder: "."
public_folder: "/"
site_url: https://cozy-twilight-20476f.netlify.app

collections:
  - name: pages
    label: Pages
    folder: ""
    create: false
    files:
      - name: index
        label: Home
        file: index.html
        fields:
          - { name: title, label: Title, widget: string }
          - { name: description, label: Meta Description, widget: text }
      - name: about
        label: About
        file: about.html
        fields:
          - { name: title, label: Title, widget: string }
          - { name: description, label: Meta Description, widget: text }
      - name: programmes
        label: Training Programmes
        file: programmes.html
        fields:
          - { name: title, label: Title, widget: string }
          - { name: description, label: Meta Description, widget: text }
